packages:
  - "apps/*"
  - "packages/*"

overrides:
  multer: ">=2.2.0"

allowBuilds:
  "@apollo/protobufjs": false
  "@prisma/engines": true
  "@scarf/scarf": false
  bcrypt: true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
