export enum Permission {
  ADMIN_PANEL_ACCESS = 'ADMIN_PANEL_ACCESS',

  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_BAN = 'USER_BAN',
  USER_MANAGE_ROLES = 'USER_MANAGE_ROLES',

  POST_CREATE = 'POST_CREATE',
  POST_UPDATE = 'POST_UPDATE',
  POST_DELETE = 'POST_DELETE',
  POST_PUBLISH = 'POST_PUBLISH',

  COMMENT_CREATE = 'COMMENT_CREATE',
  COMMENT_UPDATE = 'COMMENT_UPDATE',
  COMMENT_DELETE = 'COMMENT_DELETE',

  SETTINGS_READ = 'SETTINGS_READ',
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',
}
